config/routes.rb
Library::Application.routes.draw do
  get "sessions/new"

  resources :users do
    resources :books, :controller => :borrows
  end
  # first created -> highest priority.

  resources:books do
	  get 'page/:page', :action => :index, :on => :collection
	  resources :borrows
  end

  resources :sessions, :only => [:new, :create, :destroy]
  #resources :borrows

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  root :to => "books#index"
  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/book.rb
class Book < ActiveRecord::Base
	has_many :borrows
	has_many :users, :through => :borrows
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_filter :find_book, :only => [ :show, :edit, :update, :destroy ]
	def index
		@books = Book.page(params[:page]).per(5)
		@page_title = "index page, page #{params[:page]}"

		respond_to do |format|
			format.html # index.html.erb
			format.json { render :json => @books.to_json }
			format.xml { render :xml => @books.to_xml }
		end
	end

	def new
		@book = Book.new
		@page_title = 'new Book page'
	end

	def create
		@book = Book.new(params[:book])
		if @book.save
      flash[:notice] = "book #{@book.name} was successfully create"
      redirect_to :action => :index
    else
      render :action => :new
    end
	end

	def show
		#@book = Book.find(params[:id])
		@page_title = "#{@book.name} detail page"
	end

	def edit
		#@book = Book.find(params[:id])
		@page_title = "edit #{@book.name}"
	end

	def update
		#@book = Book.find(params[:id])
		if @book.update_attributes(params[:book])
      flash[:notice] = "book #{@book.name} was successfully updated"
      redirect_to :action => :show, :id => @book
    else
      render :action => :edit
    end
	end

	def destroy
		#@book = Book.find(params[:id])
		@book.destroy
    flash[:alert] = "book #{@book.name} was successfully deleted"
    redirect_to :action => :index
	end

  def find_book
    @book = Book.find(params[:id])
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<% if @book.errors.any? %>
  <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= f.label :name, "Name" %>
<%= f.text_field :name %>

<%= f.label :description, "Description" %>
<%= f.text_area :description %>

app/views/books/edit.html.erb
<%= form_for @book, :url => book_path(@book), :method => :put do |f| %>
	<%= render :partial => 'form', :locals => { :f => f } %>	

	<%= f.submit "Update" %>
<% end %>

app/views/books/index.html.erb
<ul>
	<% @books.each do |book| %>
		<li>
		<%= book.name %>
		<%= link_to "Borrow", :controller => :borrows, :action => :new, :book_id => book.id if isLogin? %>
		<%= link_to "View", book_path(book) %>
		<%= link_to "Edit", edit_book_path(book) %>
		<%= link_to "Delete", book_path(book), :method => :delete %>
		</li>
	<% end %>
</ul>
<%= paginate @books %>
<%= link_to "Create a new Book", new_book_path %>

app/views/books/new.html.erb
<%= form_for @book, :url => books_path do |f| %>
	<%= render :partial => 'form', :locals => { :f => f } %>	

	<%= f.submit "Create" %>
<% end %>

app/views/books/show.html.erb
<%= @book.name %>
<%= simple_format(@book.description) %>

<p><%= link_to "Back to index", books_path %></p>