config/routes.rb
Library::Application.routes.draw do
  get "sessions/new"

  resources :users do
    resources :books, :controller => :borrows
  end
  # first created -> highest priority.

  resources:books do
	  get 'page/:page', :action => :index, :on => :collection
	  resources :borrows
  end

  resources :sessions, :only => [:new, :create, :destroy]
  #resources :borrows

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  root :to => "books#index"
  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/borrow.rb
class Borrow < ActiveRecord::Base
	belongs_to :book
	belongs_to :user
end

app/controllers/borrows_controller.rb
class BorrowsController < ApplicationController
  # GET /borrows
  # GET /borrows.json
  def index
    @borrows = Borrow.all
    @books = User.find(session[:current_user_id]).books
    @books.build unless @books

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @borrows }
    end
  end

  # GET /borrows/1
  # GET /borrows/1.json
  def show
    @borrow = Borrow.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @borrow }
    end
  end

  # GET /borrows/new
  # GET /borrows/new.json
  def new
    @book = Book.find(params[:book_id])
    user_id = session['current_user_id']
    @borrow = Borrow.create(:book_id => @book.id, :user_id => user_id)
    if(@borrow)
      redirect_to user_books_path(user_id)
    else

	    respond_to do |format|
	      format.html # new.html.erb
	      format.json { render json: @borrow }
	    end
    end
  end

  # GET /borrows/1/edit
  def edit
    @borrow = Borrow.find(params[:id])
  end

  # POST /borrows
  # POST /borrows.json
  def create
    @borrow = Borrow.new(params[:borrow])

    respond_to do |format|
      if @borrow.save
        format.html { redirect_to @borrow, notice: 'Borrow was successfully created.' }
        format.json { render json: @borrow, status: :created, location: @borrow }
      else
        format.html { render action: "new" }
        format.json { render json: @borrow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /borrows/1
  # PUT /borrows/1.json
  def update
    @borrow = Borrow.find(params[:id])

    respond_to do |format|
      if @borrow.update_attributes(params[:borrow])
        format.html { redirect_to @borrow, notice: 'Borrow was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @borrow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /borrows/1
  # DELETE /borrows/1.json
  def destroy
    @borrow = Borrow.find(params[:id])
    @borrow.destroy

    respond_to do |format|
      format.html { redirect_to borrows_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/borrows_helper.rb
module BorrowsHelper
end

app/views/borrows/_form.html.erb
<%= form_for(@borrow) do |f| %>
  <% if @borrow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@borrow.errors.count, "error") %> prohibited this borrow from being saved:</h2>

      <ul>
      <% @borrow.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :book %><br />
    <%= f.text_field :book %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :borrowed_date %><br />
    <%= f.datetime_select :borrowed_date %>
  </div>
  <div class="field">
    <%= f.label :returned_date %><br />
    <%= f.datetime_select :returned_date %>
  </div>
  <div class="field">
    <%= f.label :scheduled_return_date %><br />
    <%= f.datetime_select :scheduled_return_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/borrows/edit.html.erb
<h1>Editing borrow</h1>

<%= render 'form' %>

<%= link_to 'Show', @borrow %> |
<%= link_to 'Back', borrows_path %>

app/views/borrows/index.html.erb
<h1>Listing books</h1>

<table>
  <tr>
    <th>Book</th>
    <th>User</th>
    <th>Borrowed date</th>
    <th>Returned date</th>
    <th>Scheduled return date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= book.name %></td>
    <td><%= link_to 'Show', book_path(book) %></td>
    <td><%= link_to 'return' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Books', books_path %>

app/views/borrows/new.html.erb
<h1>New borrow</h1>

<%= render 'form' %>

<%= link_to 'Back', borrows_path %>

app/views/borrows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Book:</b>
  <%= @borrow.book %>
</p>

<p>
  <b>User:</b>
  <%= @borrow.user %>
</p>

<p>
  <b>Borrowed date:</b>
  <%= @borrow.borrowed_date %>
</p>

<p>
  <b>Returned date:</b>
  <%= @borrow.returned_date %>
</p>

<p>
  <b>Scheduled return date:</b>
  <%= @borrow.scheduled_return_date %>
</p>


<%= link_to 'Edit', edit_borrow_path(@borrow) %> |
<%= link_to 'Back', borrows_path %>